/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rekapkeuanganapp;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author arief
 */
public class DialogEditTransaksi extends javax.swing.JDialog {

    private int currentIdTransaksi = 0;

    /**
     * Creates new form DialogEditTransaksi
     */
    public DialogEditTransaksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooserEdit = new com.toedter.calendar.JDateChooser();
        cmbKategoriEdit = new javax.swing.JComboBox();
        txtJumlahEdit = new javax.swing.JTextField();
        txtDeskripsiEdit = new javax.swing.JTextField();
        btnSimpanEdit = new javax.swing.JButton();
        btnBatalEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbKategoriEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSimpanEdit.setText("Simpan");
        btnSimpanEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanEditActionPerformed(evt);
            }
        });

        btnBatalEdit.setText("Batal");
        btnBatalEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalEditActionPerformed(evt);
            }
        });

        jLabel1.setText("Kategori");

        jLabel2.setText("Jumlah");

        jLabel3.setText("Keterangan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBatalEdit)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpanEdit)
                            .addComponent(txtDeskripsiEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlahEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbKategoriEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbKategoriEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(txtJumlahEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDeskripsiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanEdit)
                    .addComponent(btnBatalEdit))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanEditActionPerformed
        // TODO add your handling code here:

    if (currentIdTransaksi == 0) {
        JOptionPane.showMessageDialog(this, "ID Transaksi tidak valid.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

        ItemKategori selectedItem = (ItemKategori) cmbKategoriEdit.getSelectedItem();
        if (selectedItem == null) {
        JOptionPane.showMessageDialog(this, "Kategori harus dipilih.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        int idKategoriBaru = selectedItem.getId();
    
        String jumlahStr = txtJumlahEdit.getText();
        String deskripsi = txtDeskripsiEdit.getText(); 
        java.util.Date utilDate = jDateChooserEdit.getDate(); 

    if (utilDate == null) {
        JOptionPane.showMessageDialog(this, "Tanggal harus diisi.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
    
    double jumlah;
    try {
        jumlah = Double.parseDouble(jumlahStr);
        if (jumlah <= 0) {
             JOptionPane.showMessageDialog(this, "Jumlah harus lebih besar dari nol.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sql = "UPDATE transaksi SET id_kategori = ?, jumlah = ?, deskripsi = ?, tanggal = ? WHERE id_transaksi = ?";
    
    try (Connection conn = KoneksiDB.getKoneksi();
         java.sql.PreparedStatement pstm = conn.prepareStatement(sql)) {
        
        pstm.setInt(1, idKategoriBaru);
        pstm.setDouble(2, jumlah);
        pstm.setString(3, deskripsi);
        pstm.setDate(4, sqlDate); 
        pstm.setInt(5, currentIdTransaksi); // Kunci UPDATE ada di sini!
        
        int affectedRows = pstm.executeUpdate();
        
        if (affectedRows > 0) {
            JOptionPane.showMessageDialog(this, "Transaksi berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // Tutup Dialog setelah sukses
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui transaksi.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error Database saat memperbarui: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSimpanEditActionPerformed

    private void btnBatalEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalEditActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogEditTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogEditTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogEditTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEditTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogEditTransaksi dialog = new DialogEditTransaksi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public class ItemKategori {
        private int id;
        private String nama;

        public ItemKategori(int id, String nama) {
            this.id = id;
            this.nama = nama;
        }

        public int getId() {
            return id;
        }

        @Override
        public String toString() {
            return nama;
        }
    }

    private void loadAllKategori() {
        cmbKategoriEdit.removeAllItems();

        String sql = "SELECT id_kategori, nama_kategori, tipe FROM kategori ORDER BY tipe, nama_kategori"; 

        try (Connection conn = KoneksiDB.getKoneksi();
             java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
             java.sql.ResultSet rs = pstm.executeQuery()) {

            while (rs.next()) {
                int id = rs.getInt("id_kategori");
                String nama = rs.getString("nama_kategori") + " (" + rs.getString("tipe") + ")";
                cmbKategoriEdit.addItem(new ItemKategori(id, nama));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat semua kategori: " + e.getMessage(), "Error DB", JOptionPane.ERROR_MESSAGE);
        }
    }

public void loadDataEdit(int id) {
    currentIdTransaksi = id;

    loadAllKategori(); 
    
    String sql = "SELECT t.jumlah, t.deskripsi, t.tanggal, k.id_kategori "
               + "FROM transaksi t JOIN kategori k ON t.id_kategori = k.id_kategori "
               + "WHERE t.id_transaksi = ?";
    
    try (Connection conn = KoneksiDB.getKoneksi();
         java.sql.PreparedStatement pstm = conn.prepareStatement(sql)) {
        
        pstm.setInt(1, id);
        
        try (java.sql.ResultSet rs = pstm.executeQuery()) {
            if (rs.next()) {

                txtJumlahEdit.setText(String.valueOf(rs.getDouble("jumlah")));
                txtDeskripsiEdit.setText(rs.getString("deskripsi"));
                jDateChooserEdit.setDate(rs.getDate("tanggal"));

                int idKategoriLama = rs.getInt("id_kategori");
                for (int i = 0; i < cmbKategoriEdit.getItemCount(); i++) {
                    ItemKategori item = (ItemKategori) cmbKategoriEdit.getItemAt(i);
                    if (item != null && item.getId() == idKategoriLama) {
                        cmbKategoriEdit.setSelectedIndex(i);
                        break;
                    }
                }
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data edit: " + e.getMessage(), "Error DB", JOptionPane.ERROR_MESSAGE);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalEdit;
    private javax.swing.JButton btnSimpanEdit;
    private javax.swing.JComboBox cmbKategoriEdit;
    private com.toedter.calendar.JDateChooser jDateChooserEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDeskripsiEdit;
    private javax.swing.JTextField txtJumlahEdit;
    // End of variables declaration//GEN-END:variables
}
