/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rekapkeuanganapp;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import java.sql.Statement;


/**
 *
 * @author arief
 */
public class FormDashboard extends javax.swing.JFrame {

    /**
     * Creates new form FormDashboard
     */
public FormDashboard() {
    initComponents();
    tampilkanGrafik();
    
    cmbKategoriPemasukan.setModel(new javax.swing.DefaultComboBoxModel<>());
    
    loadKategoriPemasukan(); 
    loadKategoriPengeluaran();
    isiFilterBulan();
    isiFilterTahun();
    
    int bulanSaatIni = java.time.LocalDate.now().getMonthValue();
    int tahunSaatIni = java.time.LocalDate.now().getYear();
    loadRiwayatTransaksi(bulanSaatIni, tahunSaatIni); 
    
    cmbFilterBulan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            filterTransaksi();
        }
    });
    cmbFilterTahun.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            filterTransaksi();
        }
    });
    
    filterTransaksi();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTabbedPaneUtama = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJumlahPemasukan = new javax.swing.JTextField();
        cmbKategoriPemasukan = new javax.swing.JComboBox();
        txtDeskripsiPemasukan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSimpanPemasukan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooserPengeluaran = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbKategoriPengeluaran = new javax.swing.JComboBox();
        txtJumlahPengeluaran = new javax.swing.JTextField();
        txtDeskripsiPengeluaran = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCatatanPengeluaran = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRiwayat = new javax.swing.JTable();
        panelSidebarRiwayat = new javax.swing.JPanel();
        cmbFilterBulan = new javax.swing.JComboBox<>();
        cmbFilterTahun = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTotalPemasukan = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTotalPengeluaran = new javax.swing.JLabel();
        lblTotalSaldo = new javax.swing.JLabel();
        lblSaldoAkhir = new javax.swing.JLabel();
        btnEditTransaksi = new javax.swing.JButton();
        btnHapusTransaksi = new javax.swing.JButton();
        btnClearFilter = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        panelBingkai = new javax.swing.JPanel();
        panelGrafik = new javax.swing.JPanel();
        panelAksi = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAkun = new javax.swing.JMenu();
        mniLogout = new javax.swing.JMenuItem();
        mniKeluar = new javax.swing.JMenuItem();
        mniHapusAkun = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneUtama.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jDateChooser1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Kategori");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Jumlah Pemasukan");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Keterangan");

        cmbKategoriPemasukan.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbKategoriPemasukan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKategoriPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKategoriPemasukanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Catatan");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnSimpanPemasukan.setBackground(new java.awt.Color(0, 102, 153));
        btnSimpanPemasukan.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnSimpanPemasukan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanPemasukan.setText("Simpan");
        btnSimpanPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPemasukanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("CATAT PEMASUKAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(btnSimpanPemasukan))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbKategoriPemasukan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtJumlahPemasukan)
                                    .addComponent(txtDeskripsiPemasukan)
                                    .addComponent(jScrollPane1)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel5)))
                .addGap(170, 170, 170))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKategoriPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlahPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDeskripsiPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(47, 47, 47)
                        .addComponent(btnSimpanPemasukan))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPaneUtama.addTab("Catat Pemasukan", jPanel2);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("CATAT PENGELUARAN");

        jDateChooserPengeluaran.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Kategori");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Jumlah Pengeluaran");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Keterangan");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setText("Catatan");

        cmbKategoriPengeluaran.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbKategoriPengeluaran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKategoriPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKategoriPengeluaranActionPerformed(evt);
            }
        });

        jTextAreaCatatanPengeluaran.setColumns(20);
        jTextAreaCatatanPengeluaran.setRows(5);
        jScrollPane2.setViewportView(jTextAreaCatatanPengeluaran);

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooserPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(cmbKategoriPengeluaran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtJumlahPengeluaran)
                                    .addComponent(txtDeskripsiPengeluaran)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel6)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jDateChooserPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbKategoriPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtJumlahPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDeskripsiPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPaneUtama.addTab("Catat Pengeluaran", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        tblRiwayat.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Tipe", "Kategori", "Jumlah", "Deskripsi"
            }
        ));
        jScrollPane3.setViewportView(tblRiwayat);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        cmbFilterBulan.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbFilterBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFilterBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterBulanActionPerformed(evt);
            }
        });

        cmbFilterTahun.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbFilterTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setText("Total Pemasukan");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setText("Filter Bulan");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setText("Filter Tahun");

        lblTotalPemasukan.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTotalPemasukan.setText("jLabel14");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setText("Total Pengeluaran");

        lblTotalPengeluaran.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTotalPengeluaran.setText("jLabel16");

        lblTotalSaldo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTotalSaldo.setText("Saldo Akhir");

        lblSaldoAkhir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblSaldoAkhir.setText("jLabel18");

        btnEditTransaksi.setBackground(new java.awt.Color(0, 102, 153));
        btnEditTransaksi.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnEditTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnEditTransaksi.setText("Edit Transaksi");
        btnEditTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTransaksiActionPerformed(evt);
            }
        });

        btnHapusTransaksi.setBackground(new java.awt.Color(0, 102, 153));
        btnHapusTransaksi.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnHapusTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusTransaksi.setText("Hapus Transaksi");
        btnHapusTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusTransaksiActionPerformed(evt);
            }
        });

        btnClearFilter.setBackground(new java.awt.Color(0, 102, 153));
        btnClearFilter.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnClearFilter.setForeground(new java.awt.Color(255, 255, 255));
        btnClearFilter.setText("Hapus Filter");
        btnClearFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSidebarRiwayatLayout = new javax.swing.GroupLayout(panelSidebarRiwayat);
        panelSidebarRiwayat.setLayout(panelSidebarRiwayatLayout);
        panelSidebarRiwayatLayout.setHorizontalGroup(
            panelSidebarRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarRiwayatLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelSidebarRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaldoAkhir)
                    .addComponent(cmbFilterBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(cmbFilterTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lblTotalPemasukan)
                    .addComponent(jLabel15)
                    .addComponent(lblTotalPengeluaran)
                    .addComponent(lblTotalSaldo)
                    .addGroup(panelSidebarRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEditTransaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapusTransaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClearFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelSidebarRiwayatLayout.setVerticalGroup(
            panelSidebarRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarRiwayatLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFilterBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFilterTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnClearFilter)
                .addGap(18, 18, 18)
                .addComponent(btnEditTransaksi)
                .addGap(18, 18, 18)
                .addComponent(btnHapusTransaksi)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPemasukan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPengeluaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldoAkhir)
                .addContainerGap())
        );

        jPanel4.add(panelSidebarRiwayat, java.awt.BorderLayout.LINE_START);

        jTabbedPaneUtama.addTab("Riwayat & Saldo", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        panelBingkai.setBackground(new java.awt.Color(255, 255, 255));
        panelBingkai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBingkai.setLayout(new java.awt.BorderLayout());

        panelGrafik.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25));
        panelGrafik.setLayout(new java.awt.BorderLayout());
        panelBingkai.add(panelGrafik, java.awt.BorderLayout.CENTER);

        jPanel5.add(panelBingkai, java.awt.BorderLayout.CENTER);

        panelAksi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelAksi.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnExport.setBackground(new java.awt.Color(0, 102, 153));
        btnExport.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        panelAksi.add(btnExport);

        jPanel5.add(panelAksi, java.awt.BorderLayout.SOUTH);

        jTabbedPaneUtama.addTab("Grafik Data", jPanel5);

        mnuAkun.setText("Akun Pengguna");
        mnuAkun.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        mniLogout.setText("Logout");
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        mnuAkun.add(mniLogout);

        mniKeluar.setText("Keluar");
        mniKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKeluarActionPerformed(evt);
            }
        });
        mnuAkun.add(mniKeluar);

        mniHapusAkun.setText("Hapus Akun");
        mniHapusAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHapusAkunActionPerformed(evt);
            }
        });
        mnuAkun.add(mniHapusAkun);

        jMenuBar1.add(mnuAkun);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneUtama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void tampilkanGrafik() {
    try {
        org.jfree.data.category.DefaultCategoryDataset dataset = new org.jfree.data.category.DefaultCategoryDataset();
        
        Connection conn = KoneksiDB.getKoneksi();
        Statement stm = conn.createStatement();
        
        int bulan = cmbFilterBulan.getSelectedIndex() + 1; 
        int tahun = Integer.parseInt(cmbFilterTahun.getSelectedItem().toString());

        String sql = "SELECT k.tipe, SUM(t.jumlah) AS total " +
                     "FROM transaksi t JOIN kategori k ON t.id_kategori = k.id_kategori " +
                     "WHERE t.id_user = " + KoneksiDB.ID_USER_AKTIF + " " +
                     "AND MONTH(t.tanggal) = " + bulan + " " +
                     "AND YEAR(t.tanggal) = " + tahun + " " +
                     "GROUP BY k.tipe";
        
        ResultSet res = stm.executeQuery(sql);
        
        boolean adaData = false;
        while (res.next()) {
            adaData = true;
            dataset.addValue(res.getDouble("total"), "Total", res.getString("tipe"));
        }
        
        JFreeChart barChart = ChartFactory.createBarChart(
            "Laporan Keuangan Bulanan", 
            "Tipe Transaksi", 
            "Jumlah (Rp)", 
            dataset, 
            org.jfree.chart.plot.PlotOrientation.VERTICAL, 
            true, true, false);
            org.jfree.chart.plot.CategoryPlot plot = barChart.getCategoryPlot();
            plot.setBackgroundPaint(java.awt.Color.WHITE);
            plot.setRangeGridlinePaint(new java.awt.Color(200, 200, 200));
            plot.setOutlineVisible(false);

            java.awt.Stroke dashed = new java.awt.BasicStroke(1.0f, java.awt.BasicStroke.CAP_BUTT, 
            java.awt.BasicStroke.JOIN_MITER, 10.0f, new float[]{2.0f}, 0.0f);
            plot.setRangeGridlineStroke(dashed);

            org.jfree.chart.renderer.category.BarRenderer renderer = (org.jfree.chart.renderer.category.BarRenderer) plot.getRenderer();
            renderer.setShadowVisible(false);
            renderer.setBarPainter(new org.jfree.chart.renderer.category.StandardBarPainter());
            renderer.setItemMargin(0.1);

            barChart.setPadding(new org.jfree.ui.RectangleInsets(20, 20, 20, 20)); 

            plot.getDomainAxis().setLowerMargin(0.2);
            plot.getDomainAxis().setUpperMargin(0.2);

            renderer.setMaximumBarWidth(0.15);

            java.awt.GradientPaint blueGrad = new java.awt.GradientPaint(
                0.0f, 0.0f, new java.awt.Color(40, 70, 110),
                0.0f, 0.0f, new java.awt.Color(79, 129, 189)
            );
            renderer.setSeriesPaint(0, blueGrad);

        
        ChartPanel chartPanel = new ChartPanel(barChart);
        
        panelGrafik.removeAll();
        if (!adaData) {
            panelGrafik.add(new javax.swing.JLabel("Data bulan ini kosong", javax.swing.SwingConstants.CENTER));
        } else {
            panelGrafik.add(chartPanel, java.awt.BorderLayout.CENTER);
        }
        
        panelGrafik.revalidate();
        panelGrafik.repaint();
        
    } catch (Exception e) {
        System.out.println("Gagal memuat grafik: " + e.getMessage());
    }
}
    
    private void isiFilterBulan() {
    String[] namaBulan = {"Januari", "Februari", "Maret", "April", "Mei", "Juni", 
                          "Juli", "Agustus", "September", "Oktober", "November", "Desember"};
    cmbFilterBulan.removeAllItems();
    for (int i = 0; i < namaBulan.length; i++) {
    cmbFilterBulan.addItem(namaBulan[i]);
    }
    cmbFilterBulan.setSelectedIndex(java.time.LocalDate.now().getMonthValue() - 1);
    }

    private void isiFilterTahun() {
    cmbFilterTahun.removeAllItems();
    String sql = "SELECT DISTINCT YEAR(tanggal) as tahun FROM transaksi WHERE id_user = ? ORDER BY tahun DESC";

    try (Connection conn = KoneksiDB.getKoneksi();
        java.sql.PreparedStatement pstm = conn.prepareStatement(sql)) {

        pstm.setInt(1, KoneksiDB.ID_USER_AKTIF);

        try (java.sql.ResultSet rs = pstm.executeQuery()) {
            while (rs.next()) {
                cmbFilterTahun.addItem(String.valueOf(rs.getInt("tahun")));
            }
        }
    } 
    
    catch (SQLException e) {
        cmbFilterTahun.addItem(String.valueOf(java.time.LocalDate.now().getYear()));
    }
        if (cmbFilterTahun.getItemCount() > 0) {
            cmbFilterTahun.setSelectedItem(String.valueOf(java.time.LocalDate.now().getYear()));
        }
    }    
    
    private void filterTransaksi() {
    if (cmbFilterBulan.getSelectedItem() == null || cmbFilterTahun.getSelectedItem() == null) {
        return; 
    }

    int bulan = cmbFilterBulan.getSelectedIndex() + 1; // Indeks 0 = Januari (Bulan 1)
    int tahun = Integer.parseInt(cmbFilterTahun.getSelectedItem().toString());

    loadRiwayatTransaksi(bulan, tahun);
    tampilkanGrafik();
}
    
    private void loadRiwayatTransaksi(int bulan, int tahun) {

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Transaksi");
    model.addColumn("Tanggal");
    model.addColumn("Tipe");
    model.addColumn("Kategori");
    model.addColumn("Jumlah");
    model.addColumn("Deskripsi");
    
    String sql = "SELECT t.id_transaksi, t.tanggal, t.jumlah, t.deskripsi, k.nama_kategori, k.tipe "
               + "FROM transaksi t JOIN kategori k ON t.id_kategori = k.id_kategori "
               + "WHERE t.id_user = ? AND MONTH(t.tanggal) = ? AND YEAR(t.tanggal) = ? "
               + "ORDER BY t.tanggal DESC";
    
    try (Connection conn = KoneksiDB.getKoneksi();
         java.sql.PreparedStatement pstm = conn.prepareStatement(sql)) {
        
        pstm.setInt(1, KoneksiDB.ID_USER_AKTIF); 
        pstm.setInt(2, bulan);
        pstm.setInt(3, tahun);
        
        try (java.sql.ResultSet rs = pstm.executeQuery()) {
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_transaksi"),
                    rs.getDate("tanggal"),
                    rs.getString("tipe"),
                    rs.getString("nama_kategori"),
                    rs.getDouble("jumlah"), 
                    rs.getString("deskripsi")
                });
            }
            
            tblRiwayat.setModel(model);
            hitungSaldo(bulan, tahun); // ... (memanggil saldo)...
            
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat riwayat transaksi: " + e.getMessage(), "Error DB", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void loadRiwayatTransaksi() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Transaksi");
    model.addColumn("Tanggal");
    model.addColumn("Tipe");
    model.addColumn("Kategori");
    model.addColumn("Jumlah");
    model.addColumn("Deskripsi");

    // Query tanpa filter MONTH dan YEAR agar semua data muncul
    String sql = "SELECT t.id_transaksi, t.tanggal, t.jumlah, t.deskripsi, k.nama_kategori, k.tipe "
               + "FROM transaksi t JOIN kategori k ON t.id_kategori = k.id_kategori "
               + "WHERE t.id_user = ? "
               + "ORDER BY t.tanggal DESC";

    try (Connection conn = KoneksiDB.getKoneksi();
         java.sql.PreparedStatement pstm = conn.prepareStatement(sql)) {
        
        pstm.setInt(1, KoneksiDB.ID_USER_AKTIF); 

        try (java.sql.ResultSet rs = pstm.executeQuery()) {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_transaksi"),
                    rs.getDate("tanggal"),
                    rs.getString("tipe"),
                    rs.getString("nama_kategori"),
                    rs.getDouble("jumlah"), 
                    rs.getString("deskripsi")
                });
            }
            tblRiwayat.setModel(model);
            
            // Hitung saldo total tanpa filter bulan/tahun
            hitungTotalSaldoKeseluruhan(); 
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat semua data: " + e.getMessage());
    }
}
    
    private void hitungSaldo(int bulan, int tahun) {
    double totalPemasukan = 0;
    double totalPengeluaran = 0;
    
    // ... (filter bulan/tahun)...
    String sqlPemasukan = "SELECT SUM(t.jumlah) AS total FROM transaksi t "
                        + "JOIN kategori k ON t.id_kategori = k.id_kategori "
                        + "WHERE t.id_user = ? AND k.tipe = 'Pemasukan' AND MONTH(t.tanggal) = ? AND YEAR(t.tanggal) = ?";
    
    String sqlPengeluaran = "SELECT SUM(t.jumlah) AS total FROM transaksi t "
                          + "JOIN kategori k ON t.id_kategori = k.id_kategori "
                          + "WHERE t.id_user = ? AND k.tipe = 'Pengeluaran' AND MONTH(t.tanggal) = ? AND YEAR(t.tanggal) = ?";

    try (Connection conn = KoneksiDB.getKoneksi()) {
        
        // ... (Hitung Pemasukan)...
        try (java.sql.PreparedStatement pstm = conn.prepareStatement(sqlPemasukan)) {
            pstm.setInt(1, KoneksiDB.ID_USER_AKTIF);
            pstm.setInt(2, bulan); 
            pstm.setInt(3, tahun);
            // ... (execution code) ...
            try (java.sql.ResultSet rs = pstm.executeQuery()) {
                if (rs.next()) { totalPemasukan = rs.getDouble("total"); }
            }
        }
        
        // ... (Hitung Pengeluaran)...
        try (java.sql.PreparedStatement pstm = conn.prepareStatement(sqlPengeluaran)) {
            pstm.setInt(1, KoneksiDB.ID_USER_AKTIF);
            pstm.setInt(2, bulan); 
            pstm.setInt(3, tahun); 
            // ... (execution code)...
            try (java.sql.ResultSet rs = pstm.executeQuery()) {
                if (rs.next()) { totalPengeluaran = rs.getDouble("total"); }
            }
        }
        
        double saldoAkhir = totalPemasukan - totalPengeluaran;

        lblTotalPemasukan.setText(String.format("Rp %,.2f", totalPemasukan));
        lblTotalPengeluaran.setText(String.format("Rp %,.2f", totalPengeluaran));
        lblSaldoAkhir.setText(String.format("Rp %,.2f", saldoAkhir));
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menghitung saldo: " + e.getMessage(), "Error DB", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void hitungTotalSaldoKeseluruhan() {
    double totalPemasukan = 0;
    double totalPengeluaran = 0;

    String sqlPemasukan = "SELECT SUM(t.jumlah) AS total FROM transaksi t "
                        + "JOIN kategori k ON t.id_kategori = k.id_kategori "
                        + "WHERE t.id_user = ? AND k.tipe = 'Pemasukan'";
    
    String sqlPengeluaran = "SELECT SUM(t.jumlah) AS total FROM transaksi t "
                        + "JOIN kategori k ON t.id_kategori = k.id_kategori "
                        + "WHERE t.id_user = ? AND k.tipe = 'Pengeluaran'";

    try (Connection conn = KoneksiDB.getKoneksi()) {
        try (java.sql.PreparedStatement pstm = conn.prepareStatement(sqlPemasukan)) {
            pstm.setInt(1, KoneksiDB.ID_USER_AKTIF);
            try (java.sql.ResultSet rs = pstm.executeQuery()) {
                if (rs.next()) totalPemasukan = rs.getDouble("total");
            }
        }

        try (java.sql.PreparedStatement pstm = conn.prepareStatement(sqlPengeluaran)) {
            pstm.setInt(1, KoneksiDB.ID_USER_AKTIF);
            try (java.sql.ResultSet rs = pstm.executeQuery()) {
                if (rs.next()) totalPengeluaran = rs.getDouble("total");
            }
        }

        lblTotalPemasukan.setText("Rp " + String.format("%,.0f", totalPemasukan));
        lblTotalPengeluaran.setText("Rp " + String.format("%,.0f", totalPengeluaran));
        lblSaldoAkhir.setText("Rp " + String.format("%,.0f", (totalPemasukan - totalPengeluaran)));

    } catch (SQLException e) {
        System.out.println("Error hitung saldo total: " + e.getMessage());
    }
}
    
    private void btnSimpanPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPemasukanActionPerformed
        // TODO add your handling code here:
    int idUser = KoneksiDB.ID_USER_AKTIF; 
    if (idUser == 0) {
        JOptionPane.showMessageDialog(this, "Sesi habis. Silakan Login ulang.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    ItemKategori selectedItem = (ItemKategori) cmbKategoriPemasukan.getSelectedItem();
    if (selectedItem == null) {
        JOptionPane.showMessageDialog(this, "Kategori harus dipilih.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    int idKategori = selectedItem.getId(); 

    String jumlahStr = txtJumlahPemasukan.getText();
    String deskripsi = txtDeskripsiPemasukan.getText() + " | Catatan Tambahan: " + jTextArea1.getText();

    java.util.Date utilDate = jDateChooser1.getDate();
    if (utilDate == null) {
        JOptionPane.showMessageDialog(this, "Tanggal harus diisi!.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime()); // Konversi ke format SQL Date

    double jumlah;
    try {
        jumlah = Double.parseDouble(jumlahStr);
        if (jumlah <= 0) {
             JOptionPane.showMessageDialog(this, "Jumlah harus lebih besar dari nol.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sql = "INSERT INTO transaksi (id_user, id_kategori, jumlah, deskripsi, tanggal) VALUES (?, ?, ?, ?, ?)";
    
    try (Connection conn = KoneksiDB.getKoneksi();
         java.sql.PreparedStatement pstm = conn.prepareStatement(sql)) {
        
        pstm.setInt(1, idUser);
        pstm.setInt(2, idKategori);
        pstm.setDouble(3, jumlah);
        pstm.setString(4, deskripsi);
        pstm.setDate(5, sqlDate); 
        
        int affectedRows = pstm.executeUpdate();
        
    if (affectedRows > 0) {
        JOptionPane.showMessageDialog(this, "Pemasukan berhasil dicatat!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        filterTransaksi();
        
        txtJumlahPemasukan.setText("");
        txtDeskripsiPemasukan.setText("");
        jTextArea1.setText(""); 
        jDateChooser1.setDate(null);
            
    } else {
        JOptionPane.showMessageDialog(this, "Pemasukan gagal dicatat.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error Database saat mencatat: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSimpanPemasukanActionPerformed

    private void cmbKategoriPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKategoriPemasukanActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_cmbKategoriPemasukanActionPerformed

    private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        // TODO add your handling code here:
    KoneksiDB.ID_USER_AKTIF = 0; 
    FormLogin login = new FormLogin();
    login.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_mniLogoutActionPerformed

    private void mniKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKeluarActionPerformed
        // TODO add your handling code here:
    System.exit(0);
    }//GEN-LAST:event_mniKeluarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int idUser = KoneksiDB.ID_USER_AKTIF; 
    if (idUser == 0) {
        JOptionPane.showMessageDialog(this, "Sesi habis. Silakan Login ulang.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    ItemKategori selectedItem = (ItemKategori) cmbKategoriPengeluaran.getSelectedItem(); 
    if (selectedItem == null) {
        JOptionPane.showMessageDialog(this, "Kategori Pengeluaran harus dipilih.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    int idKategori = selectedItem.getId(); 

    String jumlahStr = txtJumlahPengeluaran.getText(); 
    String deskripsi = txtDeskripsiPengeluaran.getText() + " | Catatan Tambahan: " + jTextAreaCatatanPengeluaran.getText();
    
    java.util.Date utilDate = jDateChooserPengeluaran.getDate();
    if (utilDate == null) {
        JOptionPane.showMessageDialog(this, "Tanggal harus diisi.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
    
    double jumlah;
    try {
        jumlah = Double.parseDouble(jumlahStr);
        if (jumlah <= 0) {
             JOptionPane.showMessageDialog(this, "Jumlah harus lebih besar dari nol.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    String sql = "INSERT INTO transaksi (id_user, id_kategori, jumlah, deskripsi, tanggal) VALUES (?, ?, ?, ?, ?)";
    
    try (Connection conn = KoneksiDB.getKoneksi();
         java.sql.PreparedStatement pstm = conn.prepareStatement(sql)) {
        
        pstm.setInt(1, idUser);
        pstm.setInt(2, idKategori);
        pstm.setDouble(3, jumlah);
        pstm.setString(4, deskripsi);
        pstm.setDate(5, sqlDate); 
        
        int affectedRows = pstm.executeUpdate();
        
    if (affectedRows > 0) {
        JOptionPane.showMessageDialog(this, "Pengeluaran berhasil dicatat!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        filterTransaksi();
            
        txtJumlahPengeluaran.setText("");
        txtDeskripsiPengeluaran.setText("");
        jTextAreaCatatanPengeluaran.setText(""); 
        jDateChooserPengeluaran.setDate(null);
    } else {
        JOptionPane.showMessageDialog(this, "Pengeluaran gagal dicatat.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error Database saat mencatat Pengeluaran: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    tampilkanGrafik();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbKategoriPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKategoriPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKategoriPengeluaranActionPerformed

    private void btnEditTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTransaksiActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRiwayat.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris transaksi yang ingin diedit.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    int idTransaksi = (int) tblRiwayat.getModel().getValueAt(selectedRow, 0); 
    
    try {
        DialogEditTransaksi editDialog = new DialogEditTransaksi(this, true); 
        editDialog.loadDataEdit(idTransaksi); 
        editDialog.setVisible(true);
        filterTransaksi(); 
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error saat membuka jendela edit: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEditTransaksiActionPerformed

    private void btnHapusTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusTransaksiActionPerformed
        // TODO add your handling code here:
    int selectedRow = tblRiwayat.getSelectedRow(); 
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris transaksi yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    int idTransaksi = (int) tblRiwayat.getModel().getValueAt(selectedRow, 0); 
    int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Anda yakin ingin menghapus transaksi ID " + idTransaksi + "?", 
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    
    if (konfirmasi == JOptionPane.YES_OPTION) {
        String sql = "DELETE FROM transaksi WHERE id_transaksi = ?";
        
    try (Connection conn = KoneksiDB.getKoneksi();
        java.sql.PreparedStatement pstm = conn.prepareStatement(sql)) {
            
        pstm.setInt(1, idTransaksi);
            
        int affectedRows = pstm.executeUpdate();
            
        if (affectedRows > 0) {
            JOptionPane.showMessageDialog(this, "Transaksi berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            filterTransaksi(); 
        } 
        else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus transaksi.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } 
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error Database saat menghapus: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnHapusTransaksiActionPerformed

    private void mniHapusAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHapusAkunActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "PERINGATAN KERAS! Tindakan ini TIDAK DAPAT DIBATALKAN.\nSemua data transaksi Anda akan hilang.\nAnda yakin ingin menghapus akun?", 
            "Konfirmasi Hapus Akun", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    
    if (konfirmasi == JOptionPane.YES_OPTION) {
        String sql = "DELETE FROM user WHERE id_user = ?";
        
        try (Connection conn = KoneksiDB.getKoneksi();
             java.sql.PreparedStatement pstm = conn.prepareStatement(sql)) {
            
            pstm.setInt(1, KoneksiDB.ID_USER_AKTIF);
            
            int affectedRows = pstm.executeUpdate();
            
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Akun berhasil dihapus. Sampai jumpa!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                
                KoneksiDB.ID_USER_AKTIF = 0;
                FormLogin login = new FormLogin();
                login.setVisible(true);
                this.dispose(); 
                
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus akun. Akun mungkin tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error Database: Gagal menghapus akun. (Pastikan relasi Foreign Key sudah ON DELETE CASCADE)", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_mniHapusAkunActionPerformed

    private void cmbFilterBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFilterBulanActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setDialogTitle("Simpan Laporan Keuangan");


        javax.swing.filechooser.FileNameExtensionFilter pdfFilter = new javax.swing.filechooser.FileNameExtensionFilter("PDF Document (.pdf)", "pdf");
        javax.swing.filechooser.FileNameExtensionFilter csvFilter = new javax.swing.filechooser.FileNameExtensionFilter("Excel CSV (.csv)", "csv");
    
        fc.addChoosableFileFilter(pdfFilter);
        fc.addChoosableFileFilter(csvFilter);
        fc.setAcceptAllFileFilterUsed(false);

    if (fc.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
        String path = fc.getSelectedFile().getAbsolutePath();
        
        if (fc.getFileFilter() == pdfFilter) {
            if (!path.toLowerCase().endsWith(".pdf")) path += ".pdf";
            exportKePDF(path);
        } else {
            if (!path.toLowerCase().endsWith(".csv")) path += ".csv";
            exportKeCSV(path);
        }
    }
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnClearFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFilterActionPerformed
    // TODO add your handling code here:
    cmbFilterBulan.setSelectedIndex(0);
    cmbFilterTahun.setSelectedIndex(0);

    loadRiwayatTransaksi(); 
    tampilkanGrafik();
    
    JOptionPane.showMessageDialog(null, "Filter dihapus, menampilkan semua data.");
    }//GEN-LAST:event_btnClearFilterActionPerformed

    private void exportKePDF(String path) {
    try {
        boolean cetak = tblRiwayat.print(javax.swing.JTable.PrintMode.FIT_WIDTH, 
                new java.text.MessageFormat("Laporan Keuangan Bulanan"), 
                new java.text.MessageFormat("Halaman {0}"));
        if (cetak) {
            JOptionPane.showMessageDialog(this, "Laporan PDF berhasil disimpan!");
        }
    } catch (java.awt.print.PrinterException e) {
        JOptionPane.showMessageDialog(this, "Gagal export PDF: " + e.getMessage());
    }
}
    
    private void exportKeCSV(String path) {
    try (java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.File(path))) {
        for (int i = 0; i < tblRiwayat.getColumnCount(); i++) {
            pw.print(tblRiwayat.getColumnName(i) + (i == tblRiwayat.getColumnCount() - 1 ? "" : ","));
        }
        pw.println();

        for (int i = 0; i < tblRiwayat.getRowCount(); i++) {
            for (int j = 0; j < tblRiwayat.getColumnCount(); j++) {
                String val = tblRiwayat.getValueAt(i, j).toString();
                pw.print(val.replace(",", "") + (j == tblRiwayat.getColumnCount() - 1 ? "" : ","));
            }
            pw.println();
        }
        JOptionPane.showMessageDialog(this, "Laporan CSV (Excel) berhasil disimpan!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal export CSV: " + e.getMessage());
    }
}
    
    private void loadKategoriPemasukan() {    
    cmbKategoriPemasukan.removeAllItems();     
    String sql = "SELECT id_kategori, nama_kategori FROM kategori WHERE tipe = 'Pemasukan'";
    
    try (Connection conn = KoneksiDB.getKoneksi();
         java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
         java.sql.ResultSet rs = pstm.executeQuery()) {
        
        while (rs.next()) {
            int id = rs.getInt("id_kategori");
            String nama = rs.getString("nama_kategori");
            cmbKategoriPemasukan.addItem(new ItemKategori(id, nama));
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat kategori: " + e.getMessage(), "Error DB", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadKategoriPengeluaran() {
        cmbKategoriPengeluaran.removeAllItems(); 
        String sql = "SELECT id_kategori, nama_kategori FROM kategori WHERE tipe = 'Pengeluaran'";
    
        try (Connection conn = KoneksiDB.getKoneksi();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pstm.executeQuery()) {
        
            while (rs.next()) {
                int id = rs.getInt("id_kategori");
                String nama = rs.getString("nama_kategori");
                cmbKategoriPengeluaran.addItem(new ItemKategori(id, nama)); 
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat kategori Pengeluaran: " + e.getMessage(), "Error DB", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearFilter;
    private javax.swing.JButton btnEditTransaksi;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHapusTransaksi;
    private javax.swing.JButton btnSimpanPemasukan;
    private javax.swing.JComboBox<String> cmbFilterBulan;
    private javax.swing.JComboBox<String> cmbFilterTahun;
    private javax.swing.JComboBox cmbKategoriPemasukan;
    private javax.swing.JComboBox cmbKategoriPengeluaran;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooserPengeluaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneUtama;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaCatatanPengeluaran;
    private javax.swing.JLabel lblSaldoAkhir;
    private javax.swing.JLabel lblTotalPemasukan;
    private javax.swing.JLabel lblTotalPengeluaran;
    private javax.swing.JLabel lblTotalSaldo;
    private javax.swing.JMenuItem mniHapusAkun;
    private javax.swing.JMenuItem mniKeluar;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenu mnuAkun;
    private javax.swing.JPanel panelAksi;
    private javax.swing.JPanel panelBingkai;
    private javax.swing.JPanel panelGrafik;
    private javax.swing.JPanel panelSidebarRiwayat;
    private javax.swing.JTable tblRiwayat;
    private javax.swing.JTextField txtDeskripsiPemasukan;
    private javax.swing.JTextField txtDeskripsiPengeluaran;
    private javax.swing.JTextField txtJumlahPemasukan;
    private javax.swing.JTextField txtJumlahPengeluaran;
    // End of variables declaration//GEN-END:variables
}

    class ItemKategori { 
    private int id;
    private String nama;

    public ItemKategori(int id, String nama) {
        this.id = id;
        this.nama = nama;
    }

    public int getId() {
        return id;
    }
    
    @Override
    public String toString() {
        return nama; 
    }
}